development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_debelopment
  pool: 5
  username: takaaki
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  pool: 5
  username: takaaki
  password: 

production:
  adapter: postgresql
  database: sample_app_production
  pool: 5
  username: sample_app
  password: 
